# Generated by Django 4.1.1 on 2022-10-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poject',
            new_name='Project',
        ),
    ]
